#!/usr/bin/env php
<?php

use Major\PluralRules\Dev;
use NunoMaduro\Collision\Provider;
use Symfony\Component\Console\Application;

require __DIR__ . '/vendor/autoload.php';

(new Provider())->register();

$application = new Application('pluralrules locale data compiler');

$application->addCommands([
    new Dev\Rules\CompileRulesCommand(),
    new Dev\Tests\CompileTestsCommand(),
]);

$application->run();
