#!/usr/bin/env php
<?php

use NunoMaduro\Collision\Provider;
use Symfony\Component\Console\Application;
use Major\PluralRules\Dev\Commands;

require __DIR__ . '/vendor/autoload.php';

(new Provider())->register();

$application = new Application('pluralrules locale data compiler');

$application->addCommands([
    new Commands\CompileRulesCommand(),
    new Commands\CompileTestsCommand(),
]);

$application->run();
